theme: jekyll-theme-minimal
title: ADA 2024 Project - LeonardoDataVinci
description: Investigating seasonal fluctuations in beer ratings
repository: epfl-ada/ada-2024-project-leonardodatavinci
show_downloads: True
baseurl: "/ada-2024-project-leonardodatavinci" # Repository name for GitHub Pages
url: "https://epfl-ada.github.io"             # GitHub Pages domain
navigation:
  - title: Home
    url: /
  - title: Example
    url: /example
