name: ada-project
channels:
  - conda-forge
dependencies:
  - pandas
  - plotly
  - tqdm
  - numpy
  - folium
  - jupyter
  - ipykernel
  - matplotlib
  - seaborn
  - scikit-learn
  - pyarrow
  - pip
  - pip:
      - pycountry-convert